metrics_enabled: false
debug: true
graphite:
  host: carbon.hostedgraphite.com
  api_key: 7509c0ff-4db5-4cae-91ee-6e78ff13b336
  reporting_interval_in_seconds: 30
  include_metrics:
    - org.skife
    - xx-responses
    - com.hello

common_db:
  driverClass: org.postgresql.Driver
  user: ingress_user
  password: hello ingress user
  url: jdbc:postgresql://chanku-test.cdawj8qazvva.us-east-1.rds.amazonaws.com:5432/chanku
  properties:
    hibernate.dialect: org.hibernate.spatial.dialect.postgis.PostgisDialect

  # any properties specific to your JDBC driver:
  properties:
    charSet: UTF-8

  # the maximum amount of time to wait on an empty pool before throwing an exception
  maxWaitForConnection: 1s

  # the SQL query to run when validating a connection's liveness
  validationQuery: "/* MyService Health Check */ SELECT 1"

  initialSize: 2

  # the minimum number of connections to keep open
  minSize: 2

  # the maximum number of connections to keep open
  maxSize: 8

  # whether or not idle connections should be validated
  checkConnectionWhileIdle: false

  # the amount of time to sleep between runs of the idle connection validation, abandoned cleaner and idle pool resizing
  evictionInterval: 10s

  # the minimum amount of time an connection must sit idle in the pool before it is eligible for eviction
  minIdleTime: 1 minute

insights_db:
  driverClass: org.postgresql.Driver
  user: ingress_user
  password: hello ingress user
  url: jdbc:postgresql://chanku-test.cdawj8qazvva.us-east-1.rds.amazonaws.com:5432/chanku
  properties:
    hibernate.dialect: org.hibernate.spatial.dialect.postgis.PostgisDialect

  # any properties specific to your JDBC driver:
  properties:
    charSet: UTF-8

  # the maximum amount of time to wait on an empty pool before throwing an exception
  maxWaitForConnection: 1s

  # the SQL query to run when validating a connection's liveness
  validationQuery: "/* MyService Health Check */ SELECT 1"

  initialSize: 2

  # the minimum number of connections to keep open
  minSize: 2

  # the maximum number of connections to keep open
  maxSize: 8

  # whether or not idle connections should be validated
  checkConnectionWhileIdle: false

  # the amount of time to sleep between runs of the idle connection validation, abandoned cleaner and idle pool resizing
  evictionInterval: 10s

  # the minimum amount of time an connection must sit idle in the pool before it is eligible for eviction
  minIdleTime: 1 minute

# to allow queries with clocks out of sync
# 12 * 3600s = 43200 sec -> 12h window
allowed_query_range_seconds: 43200

sleep_sound_cache_seconds: 5
sleep_sound_duration_cache_seconds: 5

server:
  adminMinThreads: 1
  adminMaxThreads: 64
  adminContextPath: /
  applicationContextPath: /
  applicationConnectors:
    - type: http
      port: 9999
      idleTimeout: 25 seconds
  adminConnectors:
    - type: http
      port: 9998
      idleTimeout: 25 seconds
  requestLog:
    appenders:
      - type: file
        currentLogFilename: /var/log/suripu-app/suripu-app-access.log
        threshold: ALL
        archive: true
        archivedLogFilenamePattern: /var/log/suripu-app/suripu-app-access-%d{yyyy-MM-dd}.log.gz
        archivedFileCount: 7
      - type: papertrail
        host: logs2.papertrailapp.com
        port: 11366
        ident: suripu-app-dev

logging:
  level: INFO
  loggers:
    com.hello.suripu: DEBUG
    com.amazonaws: WARN
    org.whispersystems: DEBUG
  appenders:
    - type: file
      threshold: DEBUG
      currentLogFilename: /var/log/suripu-app/suripu-app.log
      archivedLogFilenamePattern: /var/log/suripu-app/suripu-app-%d{yyyy-MM-dd}.log.gz
      archivedFileCount: 7
    - type: papertrail
      host: logs2.papertrailapp.com
      port: 11366
      ident: suripu-app-dev
      # timezone: UTC
      # facility: USER
      # sendLocalName: true

score_threshold : 15 # minutes bucket for sleep-scores

push_notifications:
  arns:
    ios: arn:aws:sns:us-east-1:053216739513:app/APNS/hello-sense-ios-dev
    android: arn:aws:sns:us-east-1:053216739513:app/GCM/hello-sense-android-dev

  table_name: notifications #deprecate later

messeji_http_client:
  endpoint: "http://internal-internal-messeji-dev-1279589514.us-east-1.elb.amazonaws.com:80"
  http_client_config:
    keepAlive: 0s

taimurain_http_client:
  endpoint: http://internal-taimurain-prod-1606459001.us-east-1.elb.amazonaws.com:80
  http_client_config:
    keepAlive: 0s
    timeout: 10000ms

question_configs:
  num_skips : 5

timeline_algorithm_configuration:
  artificial_light_start_time: "21:30"
  artificial_light_stop_time: "05:00"

# store sleep scores and other stats
# v0.2: score uses movement and duration
sleep_stats_version: v_0_2
sleep_score_version: v_0_1
agg_stats_version: v_0_1

max_cache_refresh_days: 20

timeline_model_ensembles:
  bucket: hello-timeline-models
  key: normal4ensemble.base64

timeline_seed_model:
  bucket: hello-timeline-models
  key: normal4.base64

email:
   api_key: XnAIQfmDpMYIapDWGigfwA
   link_host: https://account.hello.is/password_update

rate_limiter:
  tokens_allowed_per_second: 100

kinesis:
  endpoint : https://kinesis.us-east-1.amazonaws.com
  streams :
    audio_features : audio_features
    activity_stream : activity_stream
    registrations: registrations
    encode_audio : encode_audio
    batch_pill_data : batch_pill_data
    sense_sensors_data : sense_sensors_data
    logs : logs

photo_upload:
  bucket_name: hello-accounts
  profile_prefix: photos/profile/
  max_upload_size_bytes: 5120000 # 5MB

keys_management_service:
  endpoint: https://kms.us-east-1.amazonaws.com
  keys:
    uuid: arn:aws:kms:us-east-1:053216739513:key/1c60acdc-0628-4f8f-8fbc-f1cacb59a845 # audio_uuid_dev
    token: arn:aws:kms:us-east-1:053216739513:key/9ab23bc3-1b49-4f02-a951-a9d97ca906bc # external app tokens

dynamodb:
  region: us-east-1
  tables:
    agg_stats: agg_stats
    alarm: alarm
    alarm_info: alarm_info
    algorithm_test: algorithm_test
    analytics_tracking: analytics_tracking
    app_stats: app_stats
    calibration: calibration
    device_data: sense_data
    feature_extraction_models: feature_extraction_models
    features: features
    file_manifest: file_manifest
    insights: insights
    insights_last_seen: insights_last_seen
    marketing_insights_seen: marketing_insights_seen
    notifications: notifications
    online_hmm_models: online_hmm_models
    ota_history: ota_history
    password_reset: password_reset
    pill_data: pill_data
    pill_heartbeat: pill_heartbeat
    pill_key_store: pill_key_store
    preferences: preferences
    profile_photo: profile_photo
    push_notification_event: push_notification_event
    ring_time: ring_time
    ring_time_history: ring_history_by_account
    sense_events: event
    sense_key_store: key_store
    sense_last_seen: sense_last_seen
    sense_state: sense_state
    sleep_hmm: sleephmm
    sleep_score: sleep_score
    sleep_score_parameters: sleep_score_parameters
    sleep_stats: sleep_stats
    smart_alarm_log: smart_alarm_log
    speech_results: speech_results
    speech_timeline: speech_timeline
    swap_intents: swap_intents
    sync_response_commands: response_commands
    teams: teams
    timeline: timeline
    timeline_log: timeline_log
    timezone_history: timezone_history
    wifi_info: wifi_info

  endpoints:
    agg_stats: http://dynamodb.us-east-1.amazonaws.com
    alarm: http://dynamodb.us-east-1.amazonaws.com
    alarm_info: http://dynamodb.us-east-1.amazonaws.com
    algorithm_test: http://dynamodb.us-east-1.amazonaws.com
    analytics_tracking: http://dynamodb.us-east-1.amazonaws.com
    app_stats: http://dynamodb.us-east-1.amazonaws.com
    calibration: http://dynamodb.us-east-1.amazonaws.com
    device_data: http://dynamodb.us-east-1.amazonaws.com
    feature_extraction_models: http://dynamodb.us-east-1.amazonaws.com
    features: http://dynamodb.us-east-1.amazonaws.com
    file_manifest: http://dynamodb.us-east-1.amazonaws.com
    insights: http://dynamodb.us-east-1.amazonaws.com
    insights_last_seen: http://dynamodb.us-east-1.amazonaws.com
    marketing_insights_seen: http://dynamodb.us-east-1.amazonaws.com
    notifications: http://dynamodb.us-east-1.amazonaws.com
    online_hmm_models: http://dynamodb.us-east-1.amazonaws.com
    ota_history: http://dynamodb.us-east-1.amazonaws.com
    password_reset: http://dynamodb.us-east-1.amazonaws.com
    pill_data: http://dynamodb.us-east-1.amazonaws.com
    pill_heartbeat: http://dynamodb.us-east-1.amazonaws.com
    pill_key_store: http://dynamodb.us-east-1.amazonaws.com
    preferences: http://dynamodb.us-east-1.amazonaws.com
    profile_photo: http://dynamodb.us-east-1.amazonaws.com
    push_notification_event: http://dynamodb.us-east-1.amazonaws.com
    ring_time_history: http://dynamodb.us-east-1.amazonaws.com
    ring_time: http://dynamodb.us-east-1.amazonaws.com
    sense_key_store: http://dynamodb.us-east-1.amazonaws.com
    sense_last_seen: http://dynamodb.us-east-1.amazonaws.com
    sense_state: http://dynamodb.us-east-1.amazonaws.com
    sleep_hmm: http://dynamodb.us-east-1.amazonaws.com
    sleep_score: http://dynamodb.us-east-1.amazonaws.com
    sleep_score_parameters: http://dynamodb.us-east-1.amazonaws.com
    sleep_stats: http://dynamodb.us-east-1.amazonaws.com
    smart_alarm_log: http://dynamodb.us-east-1.amazonaws.com
    speech_results: http://dynamodb.us-east-1.amazonaws.com
    speech_timeline: http://dynamodb.us-east-1.amazonaws.com
    swap_intents: http://dynamodb.us-east-1.amazonaws.com
    sync_response_commands: http://dynamodb.us-east-1.amazonaws.com
    teams: http://dynamodb.us-east-1.amazonaws.com
    timeline: http://dynamodb.us-east-1.amazonaws.com
    timeline_log: http://dynamodb.us-east-1.amazonaws.com
    timezone_history: http://dynamodb.us-east-1.amazonaws.com
    wifi_info: http://dynamodb.us-east-1.amazonaws.com

alexa_app_ids:
  hello_dev: amzn1.echo-sdk-ams.app.2bb48848-e785-4e9c-9e5f-6165d0ef6963
  josef_dev: amzn1.echo-sdk-ams.app.48296311-bcd4-4221-9608-390dee8ca111

expansions:
  hue_app_name: sense_staging
