metrics_enabled: true
debug: false
graphite:
  host: carbon.hostedgraphite.com
  api_key: 7509c0ff-4db5-4cae-91ee-6e78ff13b336
  reporting_interval_in_seconds: 30
  include_metrics:
    - org.skife
    - xx-responses
    - com.hello
    - is.hello
    - jvm.gc

common_db:
  driverClass: org.postgresql.Driver
  user: common
  password: hello-common
  url: jdbc:postgresql://common.cdawj8qazvva.us-east-1.rds.amazonaws.com:5432/common
  properties:
    hibernate.dialect: org.hibernate.spatial.dialect.postgis.PostgisDialect

  # any properties specific to your JDBC driver:
  properties:
    charSet: UTF-8

  # the maximum amount of time to wait on an empty pool before throwing an exception
  maxWaitForConnection: 1s

  # the SQL query to run when validating a connection's liveness
  validationQuery: "/* MyService Health Check */ SELECT 1"

  initialSize: 2

  # the minimum number of connections to keep open
  minSize: 2

  # the maximum number of connections to keep open
  maxSize: 32

  # whether or not idle connections should be validated
  checkConnectionWhileIdle: false
  checkConnectionOnBorrow: true

  # the amount of time to sleep between runs of the idle connection validation, abandoned cleaner and idle pool resizing
  evictionInterval: 10s

  # the minimum amount of time an connection must sit idle in the pool before it is eligible for eviction
  minIdleTime: 1 minute

insights_db:
  driverClass: org.postgresql.Driver
  user: common
  password: hello-common
  url: jdbc:postgresql://common.cdawj8qazvva.us-east-1.rds.amazonaws.com:5432/common
  properties:
    hibernate.dialect: org.hibernate.spatial.dialect.postgis.PostgisDialect

  # any properties specific to your JDBC driver:
  properties:
    charSet: UTF-8

  # the maximum amount of time to wait on an empty pool before throwing an exception
  maxWaitForConnection: 1s

  # the SQL query to run when validating a connection's liveness
  validationQuery: "/* MyService Health Check */ SELECT 1"

  initialSize: 2

  # the minimum number of connections to keep open
  minSize: 2

  # the maximum number of connections to keep open
  maxSize: 8

  # whether or not idle connections should be validated
  checkConnectionWhileIdle: false

  # the amount of time to sleep between runs of the idle connection validation, abandoned cleaner and idle pool resizing
  evictionInterval: 10s

  # the minimum amount of time an connection must sit idle in the pool before it is eligible for eviction
  minIdleTime: 1 minute

# to allow queries with clocks out of sync
# 12 * 3600s = 43200 sec -> 12h window
allowed_query_range_seconds: 43200

sleep_sound_cache_seconds: 30
sleep_sound_duration_cache_seconds: 30

server:
  adminMinThreads: 1
  adminMaxThreads: 64
  adminContextPath: /
  applicationContextPath: /
  applicationConnectors:
    - type: http
      port: 9999
      idleTimeout: 25 seconds
  adminConnectors:
    - type: http
      port: 9998
      idleTimeout: 25 seconds
  requestLog:
    appenders:
      - type: file
        currentLogFilename: /var/log/suripu-app/suripu-app-access.log
        threshold: ALL
        archive: true
        archivedLogFilenamePattern: /var/log/suripu-app/suripu-app-access-%d{yyyy-MM-dd}.log.gz
        archivedFileCount: 7
      - type: papertrail
        host: logs2.papertrailapp.com
        port: 11366
        ident: suripu-app-prod

logging:
  level: INFO
  loggers:
    com.hello.suripu: DEBUG
    com.amazonaws: WARN
    is.hello: DEBUG
    com.joestelmach.natty: WARN
    is.hello.supichi.resources.ping: DEBUG
  appenders:
    - type: file
      threshold: DEBUG
      currentLogFilename: /var/log/suripu-app/suripu-app.log
      archivedLogFilenamePattern: /var/log/suripu-app/suripu-app-%d{yyyy-MM-dd}.log.gz
      archivedFileCount: 7
    - type: papertrail
      host: logs2.papertrailapp.com
      port: 11366
      ident: suripu-app-prod
      # timezone: UTC
      # facility: USER
      # sendLocalName: true

score_threshold : 15 # minutes bucket for sleep-scores

push_notifications:
  arns:
    ios: arn:aws:sns:us-east-1:053216739513:app/APNS/hello-sense-ios-dev
    android: arn:aws:sns:us-east-1:053216739513:app/GCM/hello-sense-android-dev

  table_name: notifications #deprecate later

messeji_http_client:
  endpoint: "http://internal-messeji-prod-internal-510481854.us-east-1.elb.amazonaws.com:80"
  http_client_config:
    keepAlive: 0s

taimurain_configuration:
   http_client_config:
     keepAlive: 0s
     timeout: 10000ms
   endpoints:
     neural_net : http://internal-taimurain-prod-1606459001.us-east-1.elb.amazonaws.com:80
     neural_net_four_event: http://internal-taimurain-2-prod-1610962562.us-east-1.elb.amazonaws.com:80

question_configs:
  num_skips : 5

timeline_algorithm_configuration:
  artificial_light_start_time: "21:30"
  artificial_light_stop_time: "05:00"

# store sleep scores and other stats
# v0.2: score uses movement and duration
sleep_stats_version: v_0_2
sleep_score_version: v_0_1
agg_stats_version: v_0_1

max_cache_refresh_days: 20

timeline_model_ensembles:
  bucket: hello-timeline-models
  key: normal4ensemble.base64

timeline_seed_model:
  bucket: hello-timeline-models
  key: normal4.base64

email:
   api_key: XnAIQfmDpMYIapDWGigfwA
   link_host: https://account.hello.is/password_update

kinesis:
  endpoint : https://kinesis.us-east-1.amazonaws.com
  streams :
    audio_features : audio_features
    activity_stream : activity_stream
    registrations: registrations
    encode_audio : encode_audio
    batch_pill_data : batch_pill_data
    sense_sensors_data : sense_sensors_data
    logs : logs

rate_limiter:
  tokens_allowed_per_second: 20

photo_upload:
  bucket_name: hello-accounts
  profile_prefix: photos/profile/
  max_upload_size_bytes: 5120000 # 5MB

dynamodb:
  region: us-east-1
  default_endpoint: http://dynamodb.us-east-1.amazonaws.com
  tables:
    agg_stats: prod_agg_stats
    alarm: prod_alarm
    alarm_info: prod_alarm_info
    algorithm_test: prod_algorithm_test
    analytics_tracking: prod_analytics_tracking
    app_stats: prod_app_stats
    calibration: prod_calibration
    device_data: prod_sense_data
    feature_extraction_models: prod_feature_extraction_models
    features: features
    file_manifest: prod_file_manifest
    insights: prod_insights
    insights_last_seen: prod_insights_last_seen
    marketing_insights_seen: prod_marketing_insights_seen
    notifications: prod_notifications
    online_hmm_models: prod_online_hmm_models
    ota_history: ota_history
    password_reset: prod_password_reset
    pill_data: prod_pill_data
    pill_heartbeat: prod_pill_heartbeat
    pill_key_store: pill_key_store
    preferences: prod_preferences
    profile_photo: prod_profile_photo
    push_notification_event: prod_push_notification_event
    push_notification_settings: push_notification_settings
    ring_time: prod_ring_time
    ring_time_history: prod_ring_history_by_account
    sense_key_store: key_store
    sense_last_seen: prod_sense_last_seen
    sense_state: prod_sense_state
    sleep_hmm: prod_sleephmm
    sense_metadata: prod_sense_metadata
    sleep_score: prod_sleep_score
    sleep_score_parameters: prod_sleep_score_parameters
    sleep_stats: prod_sleep_stats
    smart_alarm_log: prod_smart_alarm_log
    speech_commands: prod_speech_commands
    speech_results: prod_speech_results
    speech_timeline: prod_speech_timeline
    swap_intents: prod_swap_intents
    sync_response_commands: prod_response_commands
    teams: teams
    timeline: prod_timeline
    timeline_log: prod_timeline_log
    timezone_history: prod_timezone_history
    wifi_info: prod_wifi_info
  endpoints: {}

alexa_app_ids:
  hello_dev: amzn1.echo-sdk-ams.app.2bb48848-e785-4e9c-9e5f-6165d0ef6963
  josef_dev: amzn1.echo-sdk-ams.app.48296311-bcd4-4221-9608-390dee8ca111

# only required for production
segment_write_key: UiFCuqdEpi6STaMCx3bo70Hii0XvWnOK

expansions:
  hue_app_name: sense-prod

s3_endpoint: https://s3.dualstack.us-east-1.amazonaws.com  # for kms

speech:
  enabled: true
  google_api_host: speech.googleapis.com
  google_api_port: 443

  audio_parameters:
    interim_results_preference: false
    encoding: LINEAR16 # [ENCODING_UNSPECIFIED, LINEAR16, FLAC, MULAW, AMR, AMR_WB, UNRECOGNIZED]
    buffer_size: 25600 # play around with this (3200 size = 100ms of audio at 16K SR)

  watson:
    username: ce487881-c6f6-45cf-8aa5-585554de4941
    password: 8riFzRbKOd4c
    voice: en-US_AllisonVoice
    #voice: en-US_MichaelVoice

  watson_save_audio:
    s3_bucket_name: hello-audio
    s3_audio_prefix_raw: voice/watson-text2speech/raw
    s3_audio_prefix: voice/watson-text2speech/16keq # bucket with responses sent back to Sense

  forecastio: 69ae5412a3a9bfc16a07ce05f6c7c5a5

  kinesis_producer:
    endpoint: https://kinesis.us-east-1.amazonaws.com
    region: us-east-1
    max_connections: 1
    request_timeout: 5000 # 1 sec
    record_max_buffered_time: 2000
    queue_size: 65536
    streams:
     speech_result: prod_speech_results

  sense_upload_audio:  # bucket to save audio uploaded from Sense
    s3_bucket_name: hello-voice-upload-prod
    s3_audio_prefix: sense_1_5

  memcache_hosts:
      - supichi-mc-prod.xoe7je.0001.use1.cache.amazonaws.com:11211
  # changing this will increase cache misses by 100% immediately.
  cache_prefix: v1

keys_management_service:
  endpoint: https://kms.us-east-1.amazonaws.com
  keys:
    uuid: arn:aws:kms:us-east-1:053216739513:key/554047d9-7171-4e31-9403-0d2101234775 # audio_uuid_prod
    audio: arn:aws:kms:us-east-1:053216739513:key/e9e9640b-9c47-4f17-916b-bb50f809b430 # audio_upload_prod
    token: arn:aws:kms:us-east-1:053216739513:key/2b67cc06-2780-4d11-9533-d98f6bc74033 # external app tokens prod
